GO_EASY_ON_ME=1
include theos/makefiles/common.mk

TWEAK_NAME = hook
hook_FILES = Tweak.xm
hook_FRAMEWORKS= UIKit Foundation QuartzCore 
hook_PRIVATE_FRAMEWORKS= AppSupport GraphicsServices 

include $(THEOS_MAKE_PATH)/tweak.mk
